### ISSUE TITLE
make time-dependent portion of the code more descriptive/self-explanatory

### ISSUE THREAD

**Issue by ragusa** [chi-tech/chi-tech#133]
I stubbled upon a "xs->J ". I've understood that J is the # of delayed n precurosrs groups (we used that in class ...). However, I think a more descriptive terminology should be used in the code (look at the number of groups for example).

This may just be the tip of the iceberg so please go through your code additions and make sure the variables have more explicit names throughout. Thanks

**Comment by Naktakala** [comment]
Resolved during PR #134
