### ISSUE TITLE
Transport XS - improve consistency with Chi-prompt versus Chi

### ISSUE THREAD

**Issue by Naktakala** [chi-tech/chi-tech#146]
When precursors are used, the KEigen solver uses chi, chi-delayed, nu-prompt and nu-delayed. When precursors are not used it uses chi, and nu. This implies chi is the same between the two. This needs to be corrected.

**Comment by ragusa** [comment]
- ideally, when problem = steady state and nu/chi-prompt and nu/chi-delayed are found, then compute total nu (simple sum) and total-chi (nu-weighted sum of the chi's)
- when problem = steady state and nu/chi-prompt is found but nu/chi-delayed are **not** found, then use nu-prompt as total nu and chi-prompt as total-chi but have a warning message
- when problem = steady state and user entered total nu and chi, then all good.

Many places to check there usage of chi in the code.

**Comment by Naktakala** [comment]
@zachhardy Has this issue been addressed now?

**Comment by zachhardy** [comment]
@Naktakala Yes and no... We modified the `TransportCrossSections` class to distinguish between chi and chi-prompt, but we still need to add checks to ensure the user provides the correct quantities. The `TransportCrossSections` class does not have knowledge of the type of problem being run so these will have to be checks within `LinearBoltzmann::Solver`. Perhaps we could do the following:

- Within `TransportCrossSections`, if nu/chi-prompt/delayed are provided, we can compute the total quantities
- Within `LinearBoltzmann::Solver::PerformInputChecks` we can add checks to ensure the appropriate quantities are available for the type of calculation specified.

Note: This is exactly what @ragusa mentioned in the comment above, just more verbose about implementation.

**Comment by Naktakala** [comment]
I support this. Can you @zachhardy make that happen so we can close this issue?
