### ISSUE TITLE
Use MPI_Abort() instead of exit()

### ISSUE THREAD

**Issue by wdhawkins** [chi-tech/chi-tech#164]
Not really part of the PR, but IMHO, calling exit() in an MPI code is bad form.  We really should be using MPI_Abort() (at least if we're not going to try to clean things up ourselves and we're not in a signal handler). This should probably be opened as a separate issue. Calling exit() will terminate this process, but it may also result in hung processes on this (and other) nodes.  MPI_Abort() will at least attempt to prevent that.

_Originally posted by @wdhawkins in https://github.com/chi-tech/chi-tech/pull/154#discussion_r661556316_

**Comment by Naktakala** [comment]
Addressed in #226
