### ISSUE TITLE
Move to a fission matrix formulation

### ISSUE THREAD

**Issue by zachhardy** [chi-tech/chi-tech#261]
For multi-particle transport, Chi-Tech is not currently able to handle fission in a particle agnostic way. 

Consider a neutron-gamma transport problem. Generally, this problem would be formulated as a single group structure where the first $G_n$ groups correspond to neutrons and the last $G_\gamma$ groups belong to photons. To be agnostic, the code should not have to know where one particle group structure ends and the other begins. For this example, there are fission neutron spectra for both neutron and gamma induced fission. In the current formulation, this requires the storage of the two vector spectra $\chi^{n \rightarrow n}$ and $\chi^{\gamma \rightarrow n}$. In the code, to select the correct spectra would require knowledge of which groups correspond to which particles. Instead, the aim is to shift the formulation to $\chi^{g' \rightarrow g}$ such that each incident group corresponds to an outgoing spectrum. When doing this, no knowledge of which group belongs to which particle is required. Alternatively, this can be formulated as $\sigma_f^{g' \rightarrow g} = (\chi \nu \sigma_f)^{g' \rightarrow g}$

**Comment by ragusa** [comment]
I agree.


--
Jean C. Ragusa, Ph.D.
Professor, Department of Nuclear Engineering
Associate Director, Institute for Scientific Computation
Texas A&M University
Email: ***@***.******@***.***>

Websites:
http://multiphysics.engr.tamu.edu
https://nustem.engr.tamu.edu/

College Station, TX 77843-3133
Phone: (979) 862-2033
FAX: (979) 845-6443
- - - - - - - - - - - - - - - - - - - - - - - -
TEXAS A&M UNIVERSITY | FEARLESS on Every Front

On Dec 23, 2022, at 11:04 AM, Zachary Hardy ***@***.******@***.***>> wrote:

sport problem. Generally, this problem would be formulated as a single group structure where the first $G_n$ groups correspond to neutrons and the last $G_\gamma$ groups belong to photons. To be agnostic, the code should not have to know where one particle group structure ends and the other begins. For this example, there are fission neutron spectra for both neutron and gamma induced fission. In the current formulation, this requires the storage of the two vector spectra $\chi^{n \rightarrow n}$ and $\chi^{\gamma \rightarrow n}$. In the code, to select the correct spectra would require knowledge of which groups correspond to which particles. Instead, the aim is to shift the formulation to $\chi^{g' \rightarrow g}$ such that each incident group corresponds to an outg

**Comment by Naktakala** [comment]
So basically, $\sigma_f^{g'\to g} = (\chi) \otimes (\nu \sigma_f)$. I think this is generally a good idea. 

Whoever takes this on:
- I suggest keeping the nu_sigma_f formulation in `TransportCrossSections` just adding the creation of the fission matrix during `Finalize`
- The XSs already have the member `transfer_matrices`, I would suggest we call this fission matrix `production_matrices`.
- Mods to set source routines would be needed

**Comment by ragusa** [comment]
When the fission production XS can be factored as chi times nu.sigf, we can computed the fission integral (FI = sum over all groups of {nu.sigf_g x flux-g}. In the FEM word, you also multiply by the basis function and integrate over space and FI is now a vector of length NDOFS.). Anyway, the ratio of the L2 norms of successive FI leads to the keff.

Here, my question/comment: when using fission production, there could be quite a few areas of the code that need to be amended. At that time, is it better to have an eigensolver that works with chi times nu.sigf and another one that works with fission production (there might be some code duplication but it may be more readable) or should be stick to a single eingensolver (less readable maybe, not sure). Thoughts?

**Comment by zachhardy** [comment]
@Naktakala NJOY defines things a little differently. $\chi_g$ and $\nu_g$ are both computed from $\sigma_f^{g' \rightarrow g}$ instead of the other way around. The information on this is given on page 202 of the manual in the GROUPR chapter. Encapsulated in $\sigma_f^{g' \rightarrow g}$ is energy dependence of the fission spectrum. In the manual they explicitly discuss that for low energies the fission spectrum is weakly energy dependent and that for high energies it is not.

@ragusa I think there is a middle ground that preserves readability and generality. I think we should move to a fission matrix formulation for computing the fission source term, but leave everything else as is. We can handle all of this in the reading of the cross-section files. There are a number of different scenarios we can work towards supporting:

- If a fission matrix is provided, require that the vector fission cross-sections are provided. This allows us to compute $\nu_g = \sum_{g'} \sigma_{f,g' \rightarrow g} / \sigma_{f,g}$, and from that $(\nu\sigma_f)_g$. With this we can compute fission rates and production rates.
- If no fission matrix is required, we can compute it a priori via $\sigma_{f,g' \rightarrow g} = \chi_g \otimes (\nu \sigma_f)_{g'}$. We end up with the same data available as in the previous bullet and can therefore compute the same quantities.

These would simply be additional cross-section specification options available to users to define fission data. With that, I think that we can get by having a single solver at the end of the day. Thoughts?

**Comment by Naktakala** [comment]
@zachhardy. I guess you will be taking this on since your work involves. Can you maybe look into creating a decision tree graph in the documentation page for the XSs? Other than that, feel free to move forward.

**Comment by zachhardy** [comment]
@Naktakala Yep I'll be doing this and yes I can. I've made a decision tree graph. Do you know of a place where I can learn how?

**Comment by Naktakala** [comment]
@zachhardy Check out draw-io. Example below:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/25042529/210420488-0984b91f-645a-496f-9d7b-db0e3a7961c2.png">

**Comment by zachhardy** [comment]
@Naktakala Roger that. Thanks!

**Comment by zachhardy** [comment]
This is turning out to be a bit tricky. In order to make this work we need to have production matrices $\sigma_{f, g' \rightarrow g} = \chi_{g' \rightarrow g} \nu_{g'}\sigma_{f,g'}$ or  $\sigma_{f, g' \rightarrow g} = \chi_g \otimes \nu_{g'}\sigma_{f,g'}$ to compute right-hand sides, $\sigma_f$ to compute fission rates (generally used for time step controls in our examples), and $\nu\sigma_f$ to compute $k$. The complications are outlined as follows:

- To compute the fission production matrix using the outer product definition, this requires the particle-to-particle fission spectra ( $\chi^{n \rightarrow n}$, $\chi^{n \rightarrow \gamma}$, $\chi^{\gamma \rightarrow n}$, and $\chi^{\gamma \rightarrow \gamma}$ ) and particles per fission terms ( $\nu^n$ and $\nu^\gamma$ ). To be particle agnostic it seems we have to require the specification of a production matrix. 

- For the $k$-eigenvalue solver and transient solver, we compute fission rates and fission neutron production rates. This requires us to have $\nu^n \sigma_f$ and $\sigma_f$ available. From the previous point, we would have to also require the user to specify two of $\nu^n$, $\nu^n \sigma_f$ and $\sigma_f$.
    - This implies that fission gamma production is purely wrapped up in the fission production matrix and that fission gamma production rates can not be computed as that this would require the storage of $\nu^\gamma$ or $\nu^\gamma\sigma_f$ which cannot be stacked with $\nu^n$.
    - Alternatively, we could only require $\sigma_f$ and compute $\nu^n$ from the production matrix. Preliminarily, this is not advisable.  NJOY defines $\nu_g = \sum_{g'} \sigma_{f, g \rightarrow g'} / \sigma_{f,g}$. When you compute this with NJOY outputs, you obtain zero values for $\nu$ in the low energy groups due to $\chi$ being zero. The only obvious patch that comes to mind is to set all zero values for $\nu$ to the last non-zero value. For Pu-239, at least, this overestimates $\nu^p$ by 1.5% at worst for the LANL 30 group structure. 
    
-  The delayed neutron data for neutron-induced fission and gamma-induced fission are different from one another and are only specified in vector format. How to handle this in a particle agnostic way is a bit unclear. For example, we must make sure that no neutron-induced fission precursors are produced from gamma-induced fission and vice versa. Perhaps there is a way to form a delayed production matrix as well.

This is complex enough to merit a conversation about how to structure this, let's set up a meeting.

**Comment by Naktakala** [comment]
I am trying to wrap my head around something before we meet. From NJOY:
- Don't we generally have $\chi^{n \rightarrow n}$, $\chi^{n \rightarrow \gamma}$, $\chi^{\gamma \rightarrow n}$, and $\chi^{\gamma \rightarrow \gamma}$? 
- Do we generally have $\nu^n$ and $\nu^\gamma$?
- Do all 4 the $\chi$ sum to one individually?

**Comment by zachhardy** [comment]
@Naktakala and I just spoke about this. Here is a summary of what was discussed and additional thoughts

- Found a bug in the fission matrix parser. NJOY specified a fission matrix only for the higher energy groups where $\chi$ has moderate energy dependence. For lower energy groups, they specify a single fission spectrum with a vector containing $\nu\sigma_f$ for only those low energy groups. The issue with low energy $\nu$ should be alleviated with this fix. By doing this we can compute $\nu\sigma_f$ and $\sigma_f$ from the transfer matrix by computing a column sum.

- When a production matrix formulation is implemented, we should require a fission production matrix, $\nu$ ( $\nu^p$ ), and the block structure per particle (for particle data checking purposes and post-processing reaction rates, if desired). 
    - Production matrix block will be denoted via `PRODUCTION_MOMENTS` with entries denoted in the same manner as the transfer matrices. While only isotropic fission is available, this will require no additional code to read in and will accommodate anisotropic fission data if that ever became available.
    - Block structure will be denoted as `BLOCK_STRUCTURE` and will list the last group for each particle in the simulation. This should be given before any group-wise data is encountered in the input cross-section file. This will be stored as an attribute within `chi_physics::TransportCrossSections`.
  
- Delayed neutron data will be addressed at a later date, but a delayed production matrix is likely required

**Comment by ragusa** [comment]
Agree. Feel free to make 3-way calls. I’d be happy to chime in, too.
The previous discussion (a few emails ago) had some new chi’s as transfer gprime to g. I was not very comfortable with that.

The latest iteration is much better ! Keep me in the loop!

—jean ragusa


http://multiphysics.engr.tamu.edu
http://nustem.engr.tamu.edu
-.-.-
iPhone, iTypo, iApologize.

On Jan 9, 2023, at 3:42 PM, Zachary Hardy ***@***.***> wrote:

﻿
@Naktakala and I just spoke about this. Here is a summary of what was discussed and additional thoughts Found a bug in the fission matrix parser. NJOY specified a fission matrix only for the higher energy groups where $\chi$ has moderate energy
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@Naktakala<https://urldefense.com/v3/__https://github.com/Naktakala__;!!KwNVnqRv!BCtM1A1wKfqHNGviSjIxGG7WjGRbkKoKAAuJIPzYKEGSptS0D8SXkW8ViVaM4O0BjoBh5m0WZyqzLh0k7lOw3ZZmOU8$> and I just spoke about this. Here is a summary of what was discussed and additional thoughts

  *   Found a bug in the fission matrix parser. NJOY specified a fission matrix only for the higher energy groups where $\chi$ has moderate energy dependence. For lower energy groups, they specify a single fission spectrum with a vector containing $\nu\sigma_f$ for only those low energy groups. The issue with low energy $\nu$ should be alleviated with this fix. By doing this we can compute $\nu\sigma_f$ and $\sigma_f$ from the transfer matrix by computing a column sum.

  *   When a production matrix formulation is implemented, we should require a fission production matrix, $\nu$ ( $\nu^p$ ), and the block structure per particle (for particle data checking purposes and post-processing reaction rates, if desired).

     *   Production matrix block will be denoted via PRODUCTION_MOMENTS with entries denoted in the same manner as the transfer matrices. While only isotropic fission is available, this will require no additional code to read in and will accommodate anisotropic fission data if that ever became available.
     *   Block structure will be denoted as BLOCK_STRUCTURE and will list the last group for each particle in the simulation. This should be given before any group-wise data is encountered in the input cross-section file. This will be stored as an attribute within chi_physics::TransportCrossSections.
  *   Delayed neutron data will be addressed at a later date, but a delayed production matrix is likely required

**Comment by zachhardy** [comment]
@ragusa Are you referring to the statement $\sigma_{f,g \rightarrow g'} = \chi_{g \rightarrow g'} \nu\sigma_{f,g}$? If so, this is how NJOY describes it, in essence, and is how it is formulated in some LANL codes according to some folks I'm working with. See the screenshot below. The consequence of this is that $\chi_{g \rightarrow g'} \nu\sigma_{f,g} \ne \chi_{g'} \otimes \nu\sigma_{f,g}$. The user will specify $\sigma_{f,g \rightarrow g'}$, $\nu_g$ and the block structure for multi-particle problems. From this, we can compute $\nu\sigma_{f,g}$ via a column sums of $\nu\sigma_{f,g}$ and $\sigma_{f,g}$ with the specified $\nu_g$. Then some way we use the specification of the block structure to make sure only $\nu\sigma_f$ for neutrons is used in $k$-calculations. There are a number of changes I need to make before getting to this. Once we get a little closer to this and I have started this leg of the implementation we can meet to make sure we are all on the same page.


<img width="458" alt="Screen Shot 2023-01-10 at 8 39 17 AM" src="https://user-images.githubusercontent.com/44588104/211595501-31ad4f23-7163-49e2-b3ec-8b2481aa4f32.png">
