### ISSUE TITLE
VTK power distribution and relative power distribution outputs

### ISSUE THREAD

**Issue by zachhardy** [chi-tech/chi-tech#295]
Create VTK output options for power and relative power.

--------------------------------------------------

Final note: if you think about outputing (e.g., VTK) the power distribution, have an option to output its relative value. That is, output also P_cell / P_ave where P_ave = {sum_cell P_cell V_cell} / {sum_cell V_cell}.

_Originally posted by @ragusa in https://github.com/chi-tech/chi-tech/issues/293#issuecomment-1386428244_

**Comment by Naktakala** [comment]
Completed with #335
